Traceback (most recent call last):
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 650, in async_setup_kernel
    yield
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import graph_tool.all as gt

# g = gt.collection.ns["word_assoc"]
g = gt.collection.ns["adjnoun"]
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mgraph_tool[39;00m[38;5;21;01m.[39;00m[38;5;21;01mall[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgt[39;00m
[1;32m      3[0m [38;5;66;03m# g = gt.collection.ns["word_assoc"][39;00m
[1;32m      4[0m g [38;5;241m=[39m gt[38;5;241m.[39mcollection[38;5;241m.[39mns[[38;5;124m"[39m[38;5;124madjnoun[39m[38;5;124m"[39m]

[0;31mModuleNotFoundError[0m: No module named 'graph_tool'

