Traceback (most recent call last):
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 650, in async_setup_kernel
    yield
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/cbd/.pyenv/versions/3.11.1/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# pip install pyvis

from pyvis.network import Network

# Create a NetworkX graph (you can use any existing graph)
G = nx.karate_club_graph()

# Convert the NetworkX graph to a Pyvis network
# net = Network(height='500px', width='100%', directed=True, notebook=True, cdn_resources='in_line')
net = Network(height='500px', width='100%', directed=True)
net.from_nx(G)

# Save the network as an HTML file
net.show('network.html', notebook=False)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 14[0m
[1;32m     11[0m net[38;5;241m.[39mfrom_nx(G)
[1;32m     13[0m [38;5;66;03m# Save the network as an HTML file[39;00m
[0;32m---> 14[0m [43mnet[49m[38;5;241;43m.[39;49m[43mshow[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mnetwork.html[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mnotebook[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m

[0;31mTypeError[0m: Network.show() got an unexpected keyword argument 'notebook'

